# Generated by Django 4.1.5 on 2023-02-07 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0006_alter_booking_bookingdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="BookingDate",
            field=models.DateField(
                default=datetime.datetime(2023, 2, 8, 5, 44, 46, 458139)
            ),
        ),
    ]
